# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: 'locust'
#     static_configs:
#       - targets: ['locust-exporter:9646']


scrape_configs:
- job_name: prometheus_scrapper
  scrape_interval: 5s
  static_configs:
  - targets:
    - locust-metrics-exporter:9646